### ISSUE TITLE
The link to the demos in the README is broken.

### ISSUE THREAD

**Issue by natsumesou** [yomotsu/InViewObserver#4]
You should put your examples directory in https://github.com/yomotsu/yomotsu.github.com , if you would like to publish it on yomotsu.github.io.

![スクリーンショット 2023-07-18 15 53 06](https://github.com/yomotsu/inview-observer/assets/193396/e2ce0fa0-cc44-47be-911e-3cba9a08f4dd)

**Comment by yomotsu** [comment]
Thanks for your notice.
I confirmed...And actually, the URL should be https://yomotsu.github.io/inview-observer/examples/index.html

I just fixed that with https://github.com/yomotsu/inview-observer/commit/0d739d523a8377fe0d978356c353a71bab15907f
Thanks again!
